In [55]:
import imp
imp.reload(logRegres)

<module 'logRegres' from '/Users/adamzfc/Git/demo/python_demo/machinelearninginaction/logistic/logRegres.py'>

In [40]:
import logRegres
dataArr, labelMat = logRegres.loadDataSet()
weights = logRegres.gradAscent(dataArr, labelMat)

In [59]:
# logRegres.plotBestFit(weights)

In [9]:
import numpy as np
dataMatrix = np.mat(dataArr)
np.shape(dataMatrix)

(100, 3)

In [10]:
weights

matrix([[ 4.12414349],
        [ 0.48007329],
        [-0.6168482 ]])

In [11]:
weights.getA()

array([[ 4.12414349],
       [ 0.48007329],
       [-0.6168482 ]])

In [12]:
np.arange(-3.0,3.0,0.1)

array([ -3.00000000e+00,  -2.90000000e+00,  -2.80000000e+00,
        -2.70000000e+00,  -2.60000000e+00,  -2.50000000e+00,
        -2.40000000e+00,  -2.30000000e+00,  -2.20000000e+00,
        -2.10000000e+00,  -2.00000000e+00,  -1.90000000e+00,
        -1.80000000e+00,  -1.70000000e+00,  -1.60000000e+00,
        -1.50000000e+00,  -1.40000000e+00,  -1.30000000e+00,
        -1.20000000e+00,  -1.10000000e+00,  -1.00000000e+00,
        -9.00000000e-01,  -8.00000000e-01,  -7.00000000e-01,
        -6.00000000e-01,  -5.00000000e-01,  -4.00000000e-01,
        -3.00000000e-01,  -2.00000000e-01,  -1.00000000e-01,
         2.66453526e-15,   1.00000000e-01,   2.00000000e-01,
         3.00000000e-01,   4.00000000e-01,   5.00000000e-01,
         6.00000000e-01,   7.00000000e-01,   8.00000000e-01,
         9.00000000e-01,   1.00000000e+00,   1.10000000e+00,
         1.20000000e+00,   1.30000000e+00,   1.40000000e+00,
         1.50000000e+00,   1.60000000e+00,   1.70000000e+00,
         1.80000000e+00,

In [60]:
import logRegres
dataArr, labelMat = logRegres.loadDataSet()
weights = logRegres.stocGradAscent0(dataArr, labelMat)
# logRegres.plotBestFit(weights)